# Generated by Django 5.1.3 on 2025-08-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن تیکت')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='تلفن')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
            ],
        ),
    ]
