# Generated by Django 5.1.3 on 2025-08-09 06:17

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت درخواست'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن'),
        ),
    ]
