# Generated by Django 5.1.3 on 2025-08-16 06:59

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ticket_created_at_alter_ticket_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نویسنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='متن دیدگاه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='کامنت')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_commen_created_1f5393_idx')],
            },
        ),
    ]
