# Generated by Django 5.1.3 on 2025-08-16 06:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_ticket_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اپدیت شده در'),
        ),
    ]
