# Generated by Django 5.1.3 on 2025-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_created_at_alter_comment_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, verbose_name='زمان مطالعه'),
        ),
    ]
