# Generated by Django 5.1.3 on 2025-09-06 06:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_image_created_at_alter_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=50, scale=0.5, size=[300, 300], upload_to='images/', verbose_name='تصویر'),
        ),
    ]
