# Generated by Django 6.0 on 2025-12-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت بعد از تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن کالا (گرم)'),
        ),
    ]
