# Generated by Django 5.2.4 on 2025-08-09 06:22

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ticket_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ دثبت در خواست'),
            preserve_default=False,
        ),
    ]
