# Generated by Django 5.2.4 on 2025-08-16 06:56

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_ticket_options_alter_ticket_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نویسنده')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='متن دیدگاه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name=' تاریخ درج')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name=' تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_commen_created_1f5393_idx')],
            },
        ),
    ]
