# Generated by Django 5.2.4 on 2025-09-06 06:50

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=50, scale=0.5, size=[300, 300], upload_to='images/', verbose_name='تصویر'),
        ),
    ]
