# Generated by Django 5.2.4 on 2025-10-03 13:39

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_image_description_alter_image_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[500, 500], upload_to='account_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
