# Generated by Django 5.2.4 on 2025-10-03 13:45

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
