# Generated by Django 5.2.4 on 2025-10-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'technology'), ('programming', 'programming'), ('ai', 'ai'), ('other', 'other')], default='other', max_length=100),
        ),
    ]
