# Generated by Django 5.2.3 on 2025-10-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
