# Generated by Django 5.2.4 on 2025-12-13 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_cotact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotact',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='followers', through='social.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
