# Generated by Django 5.2.4 on 2025-12-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_cotact_contact_user_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='account_images/default.png', null=True, upload_to='account_images/'),
        ),
    ]
